# -*- coding: utf-8 -*-

import wikipedia
from bs4 import BeautifulSoup


# Get list of countries in German "de" or English "en"
def getList():
    enList = []
    deList = []
    
    wikipedia.set_lang(lang)
    ldS = wikipedia.page("Liste_der_Staaten_der_Erde").html()
    
enList = ['Afghanistan', 'Albania',  'Algeria', 'American Samoa', 'Andorra',  'Angola',
           'Anguilla',  'Antarctica',  'Antigua \& Barbuda',  'Argentina',  'Armenia',
           'Aruba',  'Australia', 'Austria', 'Azerbaijan',  'Bahrain',  'Baker Is.',
           'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda',
           'Bhutan', 'Bolivia', 'Bosnia \& Herzegovina', 'Botswana', 'Bouvet Is.',
           'Brazil', 'British Indian Ocean Territory',  'British Virgin Is.',  'Brunei',
           'Bulgaria', 'Burkina Faso',  'Burundi', 'Cambodia', 'Cameroon', 'Canada',
           'Cape Verde', 'Cayman Is.', 'Central African Republic',  'Chad', 'Chile',
           'China', 'Christmas Is.', 'Cocos Is.', 'Colombia', 'Comoros',  'Republic of the Congo', 
           'Congo DRC', 'Cook Is.',  'Costa Rica', "Cote d'Ivoire",  'Croatia',
           'Cuba',  'Cyprus',  'Czech Republic',  'Denmark',  'Djibouti',  'Dominica',
           'Dominican Republic', 'Ecuador', 'Egypt',  'El Salvador',  'Equatorial Guinea',
           'Eritrea', 'Estonia', 'Ethiopia', 'Falkland Is.', 'Faroe Is.', 'Fiji',
           'Finland', 'France', 'French Guiana',  'French Polynesia',  
           'French Southern \& Antarctic Lands', 'Gabon',  'Gaza Strip',  'Georgia (country)',
           'Germany', 'Ghana', 'Gibraltar', 'Glorioso Islands', 'Greece',  'Greenland',
           'Grenada', 'Guadeloupe', 'Guam', 'Guatemala',  'Guernsey',  'Guinea',
           'Guinea-Bissau', 'Guyana', 'Haiti', 'Heard Island and McDonald Islands', 'Honduras',
           'Howland Island', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
           'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica',  'Jan Mayen',
           'Japan', 'Jarvis Island', 'Jersey', 'Johnston Atoll', 'Jordan',  'Juan De Nova Is.',
           'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia',
           'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
           'Luxembourg',  'Republic of Macedonia',  'Madagascar',  'Malawi',  'Malaysia',  'Maldives',
           'Mali', 'Malta', 'Marshall Is.',  'Martinique',  'Mauritania',  'Mauritius',
           'Mayotte', 'Mexico', 'Federated States of Micronesia', 'Midway Atoll', 'Moldova', 'Monaco', 'Mongolia',
           'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
           'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles',  'New Caledonia',
           'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island',
           'North Korea', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau',
           'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn Islands',
           'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Réunion', 'Romania','Russia',
           'Rwanda', 'Samoa', 'San Marino', 'São Tomé and Príncipe', 'Saudi Arabia',
           'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
           'Slovenia', 'Solomon Islands', 'Somalia', 'South  Africa', 
           'South Georgia and the South Sandwich Islands', 'South Korea', 'Spain',  'Sri Lanka',
           'St. Helena', 'Saint Kitts and Nevis', 'St. Lucia', 'St. Pierre \& Miquelon',
           'St. Vincent \& the Grenadines', 'Sudan','Suriname', 'Svalbard',  'Swaziland',
           'Sweden', 'Switzerland', 'Syria','Tajikistan', 'Tanzania', 'Thailand',
           'The Bahamas', 'The Gambia',  'Timor-Leste',  'Togo',  'Tokelau',  'Tonga',
           'Trinidad and Tobago', 'Tunisia', 'Turkey',  'Turkmenistan',  'Turks and Caicos Islands',
           'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 
           'United States', 'Uruguay',  'Uzbekistan',  'Vanuatu',  'Vatican City',  'Venezuela',
            'Vietnam',  'Virgin Islands.',  'Wake Island', 'Wallis and Futuna', 'West Bank',
            'Western Sahara', 'Yemen',  'Zambia', 'Zimbabwe']

deList = ['Afghanistan', 'Albanien',  'Algerien', 'Amerikanisch Samoa', 'Andorra',  'Angola',
           'Anguilla',  'Antarktis',  'Antigua \& Barbuda',  'Argentinien',  'Armenien',
           'Aruba',  'Australien', 'Österreich', 'Aserbaidschan',  'Bahrain',  'Baker Is.',
           'Bangladesch', 'Barbados', 'Belarus', 'Belgien', 'Belize', 'Benin', 'Bermuda',
           'Bhutan', 'Bolivien', 'Bosnien und Herzegowina', 'Botswana', 'Bouvet Is.',
           'Brasilien', 'Britisches Territorium im Indischen Ozean',  'Britische Jungferninseln',  'Brunei',
           'Bulgarien', 'Burkina Faso',  'Burundi', 'Kambodscha', 'Kamerun', 'Kanada',
           'Kap Verde', 'Cayman Islands.', 'Zentralafrikanische Republik',  'Tschad', 'Chile',
           'Volksrepublik China', 'Weihnachtsinsel (Australien)', 'Cocos Is.', 'Kolumbien', 'Komoren',  'Republik Kongo', 
           'Demokratische Republik Kongo', 'Cookinseln',  'Costa Rica', "Elfenbeinküste",  'Kroatien',
           'Kuba',  'Zypern',  'Tschechische Republik',  'Dänemark',  'Dschibuti',  'Dominica',
           'Dominikanische Republik', 'Ecuador', 'Ägypten',  'El Salvador',  'Äquatorialguinea',
           'Eritrea', 'Estland', 'Äthiopien', 'Falklandinseln.', 'Färöer', 'Fiji',
           'Finnland', 'Frankreich', 'Französisch-Guayana',  'Französisch Polynesien',  
           'Französische Süd- und Antarktisgebiete', 'Gabun',  'Gaza Streifen',  'Georgien',
           'Deutschland', 'Ghana', 'Gibraltar', 'Îles Glorieuses', 'Griechenland',  'Grönland',
           'Grenada', 'Guadeloupe', 'Guam', 'Guatemala',  'Guernsey',  'Guinea',
           'Guinea-Bissau', 'Guyana', 'Haiti', 'Heard und McDonaldinseln', 'Honduras',
           'Howland Is.', 'Ungarn', 'Island', 'Indien', 'Indonesien', 'Iran', 'Irak',
           'Irland', 'Isle of Man', 'Israel', 'Italien', 'Jamaika',  'Jan Mayen',
           'Japan', 'Jarvisinsel', 'Jersey', 'Johnston Atoll', 'Jordanien',  'Juan De Nova Is.',
           'Kasachstan', 'Kenia', 'Kiribati', 'Kuwait', 'Kirgisistan', 'Laos', 'Lettland',
           'Libanon', 'Lesotho', 'Liberia', 'Libyen', 'Liechtenstein', 'Litauen',
           'Luxembourg',  'Mazedonien',  'Madagaskar',  'Malawi',  'Malaysia',  'Malediven',
           'Mali', 'Malta', 'Marshallinseln',  'Martinique',  'Mauretanien',  'Mauritius',
           'Mayotte', 'Mexiko', 'Föderierte Staaten von Mikronesien', 'Midwayinseln', 'Moldawien', 'Monaco', 'Mongolei',
           'Montenegro', 'Montserrat', 'Marokko', 'Mosambik', 'Myanmar', 'Namibia',
           'Nauru', 'Nepal', 'Niederlande', 'Niederländische Antillen',  'Neukaledonien',
           'Neuseeland', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolkinsel',
           'Nord Korea', 'Nördliche Marianen', 'Norwegen', 'Oman', 'Pakistan', 'Palau',
           'Panama', 'Papua-Neuguinea', 'Paraguay', 'Peru', 'Philippinen', 'Pitcairninseln',
           'Polen', 'Portugal', 'Puerto Rico', 'Katar', 'La Reunion', 'Rumänien','Russland',
           'Ruanda', 'Samoa', 'San Marino', 'São Tomé und Príncipe', 'Saudi Arabien',
           'Senegal', 'Serbien', 'Seychellen', 'Sierra Leone', 'Singapur', 'Slowakei',
           'Slowenien', 'Salomonen', 'Somalia', 'Südafrika', 
           'Südgeorgien und die Südlichen Sandwichinseln', 'Südkorea', 'Spanien',  'Sri Lanka',
           'St. Helena (Insel)', 'St. Kitts und Nevis', 'St. Lucia', 'Saint-Pierre und Miquelon',
           'St. Vincent und die Grenadinen', 'Sudan','Suriname', 'Svalbard',  'Swasiland',
           'Schweden', 'Schweiz', 'Syrien','Tadschikistan', 'Tansania', 'Thailand',
           'Bahamas', 'Gambia',  'Osttimor',  'Togo',  'Tokelau',  'Tonga',
           'Trinidad und Tobago', 'Tunesien', 'Türkei',  'Turkmenistan',  'Turks- und Caicosinseln',
           'Tuvalu', 'Uganda', 'Ukraine', 'Vereinigte Arabische Emirate', 'Vereinigtes Königreich', 
           'Vereinigte Staaten', 'Uruguay',  'Usbekistan',  'Vanuatu',  'Vatikanstadt',  'Venezuela',
            'Vietnam',  'Jungferninseln',  'Wake', 'Wallis \& Futuna', 'Westjordanland',
            'Westsahara', 'Jemen',  'Sambia', 'Simbabwe']